"""Generate the plain-function overloads of pipe, flow and compose (two to eight
stages) and of match and rewrite (one to sixteen clauses).

Mojo 1.1 reads a plain function's signature only at a parameter of its function
type, so each stage or clause count spells one thin signature per function. Run
from the repository root; `--check` reports whether the sources match instead of
writing.

Names: `A0`...`An` are the values passing through the chain, `P1`... the parameter
types that later stages declare, `B0` and `B1` a binary first stage's arguments,
and `E0`... the stages' errors. A later stage names its own input type, so a
mismatched call still selects these overloads and reaches the pipeline's
per-stage check, which names the stage and both types.
"""
import argparse
import sys

from fp_tools.runtime import ROOT

MD = 'Movable & Deinitable'
MAX = 8
START = '# --- plain-function overloads (generated) ---\n'
END = '# --- end plain-function overloads ---\n'
MATCH_MAX = 16
MATCH_START = '# --- match overloads (generated) ---\n'
MATCH_END = '# --- end match overloads ---\n'
MATCH_HEADER = '''# Generated by scripts/generate_plain_overloads.py; edit the generator, not this
# block. A clause's signature is known only at a parameter of its function type,
# so each clause count spells one thin signature per clause. A clause's error is
# inferred as AnyType: under a value bound a pure function's error is not Never
# (see _NativeError). _Result<n> and _Error<n> spell the match's types over the
# clause types (see _match). The one-clause overload of each form carries the
# documentation.
'''
HEADER = '''# Generated by scripts/generate_plain_overloads.py; edit the generator, not this
# block. A plain function's signature is known only at a parameter of its function
# type; a variadic pack keeps the type but not the signature, so a stage's result
# cannot be inferred from it. Each stage count therefore spells one thin
# signature per stage and delegates to the variadic form. Later stages name their
# own input type (P1, P2, ...), so a mismatched call reaches the per-stage check.
# Closures use as_unary.
'''


def stage(first_arity, index):
    """Thin signature and stored _ThinFunction type of stage `index`, in run order."""
    if index == 0 and first_arity == 0:
        return 'def() raises E0 thin -> A1', '_Thin0F[A1, E0]'
    if index == 0 and first_arity == 2:
        return 'def(var B0, var B1) raises E0 thin -> A1', '_Thin2F[B0, B1, A1, E0]'
    parameter = 'A0' if index == 0 else 'P%d' % index
    return ('def(var %s) raises E%d thin -> A%d' % (parameter, index, index + 1),
            '_Thin1F[%s, A%d, E%d]' % (parameter, index + 1, index))


def decls(n, first_arity):
    names = ['B0', 'B1'] if first_arity == 2 else []
    names += ['A%d' % i for i in range(0 if first_arity == 1 else 1, n + 1)]
    names += ['P%d' % i for i in range(1, n)]
    names += ['E%d' % i for i in range(n)]
    return ', '.join('%s: %s' % (name, MD) for name in names)


def common(n):
    error = 'E0'
    for i in range(1, n):
        error = '_CommonError[%s, E%d]' % (error, i)
    return error


def pipe_overloads():
    out = []
    for n in range(2, MAX + 1):
        params = ', '.join('f%d: %s' % (i, stage(1, i)[0]) for i in range(n))
        wrapped = ', '.join('%s(f%d)' % (stage(1, i)[1], i) for i in range(n))
        out.append('\n\ndef pipe[%s, //](\n    var value: A0, %s\n) raises %s -> A%d:\n'
                   '    """Apply %d plain functions in order."""\n    return pipe[E=%s](value^, %s)\n'
                   % (decls(n, 1), params, common(n), n, n, common(n), wrapped))
    return ''.join(out)


def composition_overloads():
    out = []
    for name, reverse in (('flow', False), ('compose', True)):
        for first_arity in (1, 0, 2):
            for n in range(2, MAX + 1):
                order = list(range(n))[::-1] if reverse else list(range(n))
                params = ', '.join('f%d: %s' % (i, stage(first_arity, i)[0]) for i in order)
                types = ', '.join(stage(first_arity, i)[1] for i in order)
                wrapped = ', '.join('%s(f%d)' % (stage(first_arity, i)[1], i) for i in order)
                direction = 'right to left' if reverse else 'left to right'
                out.append('\n\ndef %s[%s, //](\n    %s\n) -> Composition[%s, %d, %s]:\n'
                           '    """Store %d plain functions, applied %s."""\n    return %s(%s)\n'
                           % (name, decls(n, first_arity), params, reverse, first_arity, types,
                              n, direction, name, wrapped))
    return ''.join(out)


# Match forms: the clause parameters each form's clauses take, and the subjects.
MATCH_FORMS = {
    'single': ('A',),
    'context': ('A', 'B'),
    'pair': ('A', 'B'),
    'triple': ('A', 'B', 'C'),
    'rewrite': ('A',),
}

MATCH_DOCS = {
    'single': ('''Match `subject` with clauses: the first that applies to it gives the result.

    Takes one to sixteen clauses. A clause is a plain function or a lambda without
    captures; its parameter type says which values it applies to, and a `when`
    clause may decline. The clauses are checked when the program compiles. The
    subject is one of:

    - a `Node[F]`: a clause takes a constructor of `F`, whose recursive fields are
      declared either as stored, `Node[F]`, or as the result type, in which case
      they arrive already matched; or it takes `Node[F]`, which accepts any
      constructor. A clause returns the result or `Next(node)`, to continue with a
      smaller value.
    - a value stored in place, such as `Choice[F]` or `Result[T, E]`: a clause
      takes a constructor, or the whole type.
    - an `Optional[T]`: a clause takes `T` for a present value, `NoneType` for an
      absent one, or `Optional[T]`.

    Parameters:
        S: The subject's type.
        A0: The clause's parameter type.
        O0: The clause's result type: the result, `Next[Node[F]]`, or a guarded result.
        E0: The clause's error type, `Never` for a pure clause.

    Args:
        subject: The value to match, borrowed.
        f0: The first clause; further clauses follow in order.

    Returns:
        The result of the first clause that applies.

    Raises:
        The clauses' common error; a match of pure clauses does not raise.
    ''', 'Match `subject` with %d clauses.'),
    'context': ('''Match `subject` with clauses that also take `context` as their second parameter.

    The context is borrowed and passed to every clause, for data the clauses need
    but the subject does not hold. Otherwise as the match without a context.

    Parameters:
        S: The subject's type.
        X: The context type.
        A0: The clause's parameter type.
        B0: The clause's second parameter type, which must be the context type.
        O0: The clause's result type: the result, `Next[Node[F]]`, or a guarded result.
        E0: The clause's error type, `Never` for a pure clause.

    Args:
        subject: The value to match.
        f0: The first clause; further clauses follow in order.
        context: The value passed to every clause.

    Returns:
        The result of the first clause that applies.

    Raises:
        The clauses' common error; a match of pure clauses does not raise.
    ''', 'Match `subject` with %d clauses that also take `context`.'),
    'pair': ('''Match two subjects together: the first clause that applies to both gives the result.

    A clause takes one parameter per subject, as for a single subject: a
    constructor (for a `Node`, as stored) or the whole type, the type of a
    present `Optional` value or `NoneType`, or for any other subject its type.
    Every combination of cases must be covered. Nothing is evaluated recursively
    and `Next` is not available.

    Parameters:
        S0: The first subject's type.
        S1: The second subject's type.
        A0: The clause's first parameter type.
        B0: The clause's second parameter type.
        O0: The clause's result type, or a guarded result.
        E0: The clause's error type, `Never` for a pure clause.

    Args:
        subjects: The values to match.
        f0: The first clause; further clauses follow in order.

    Returns:
        The result of the first clause that applies.

    Raises:
        The clauses' common error; a match of pure clauses does not raise.
    ''', 'Match two subjects with %d clauses.'),
    'triple': ('''Match three subjects together: the first clause that applies to all of them gives the result.

    As the match of two subjects, with one more parameter per clause.

    Parameters:
        S0: The first subject's type.
        S1: The second subject's type.
        S2: The third subject's type.
        A0: The clause's first parameter type.
        B0: The clause's second parameter type.
        C0: The clause's third parameter type.
        O0: The clause's result type, or a guarded result.
        E0: The clause's error type, `Never` for a pure clause.

    Args:
        subjects: The values to match.
        f0: The first clause; further clauses follow in order.

    Returns:
        The result of the first clause that applies.

    Raises:
        The clauses' common error; a match of pure clauses does not raise.
    ''', 'Match three subjects with %d clauses.'),
    'rewrite': ('''Rewrite `subject` bottom-up with clauses for the constructors that change.

    A clause takes a constructor of `F` and returns the new `Node[F]`; its
    recursive fields declared as `Node[F]` arrive already rewritten. Every other
    node is rebuilt from its rewritten children, and a node whose children did not
    change is reused, so sharing is preserved. A `when` clause may decline. The
    rewrite is a single pass.

    Parameters:
        F: The data type.
        A0: The clause's parameter type.
        O0: The clause's result type: `Node[F]`, or a guarded `Node[F]`.
        E0: The clause's error type, `Never` for a pure clause.

    Args:
        subject: The value to rewrite.
        f0: The first clause; further clauses follow in order.

    Returns:
        The rewritten value.

    Raises:
        The clauses' common error; a rewrite of pure clauses does not raise.
    ''', 'Rewrite `subject` bottom-up with %d clauses.'),
}


def clause_parts(form, n):
    """Type-parameter declarations, function parameters, result and error of `n` clauses."""
    letters = MATCH_FORMS[form]
    decls, functions = [], []
    for i in range(n):
        params = ['%s%d' % (letter, i) for letter in letters]
        decls.append(', '.join(['%s: AnyType' % p for p in params] + ['O%d: Value' % i, 'E%d: AnyType' % i]))
        functions.append('f%d: def(%s) raises E%d thin -> O%d' % (i, ', '.join(params), i, i))
    result = '_Result%d[%s]' % (n, ', '.join('O%d' % i for i in range(n)))
    error = '_Error%d[%s]' % (n, ', '.join('E%d' % i for i in range(n)))
    return decls, functions, result, error


def match_aliases():
    """The result and error of `n` clauses, spelled over the clause types."""
    out = []
    for n in range(1, MATCH_MAX + 1):
        result, error = '_NoResult', 'Never'
        for i in reversed(range(n)):
            result = '_Pick[O%d, %s]' % (i, result)
            error = '_CommonError[_NativeError[E%d], %s]' % (i, error)
        out.append('comptime _Result%d[%s]: Value = %s\n' % (n, ', '.join('O%d: Value' % i for i in range(n)), result))
        out.append('comptime _Error%d[%s]: Value = %s\n' % (n, ', '.join('E%d: AnyType' % i for i in range(n)), error))
    return '\n' + ''.join(out)


def match_overloads():
    out = [match_aliases()]
    for form in MATCH_FORMS:
        full, short = MATCH_DOCS[form]
        for n in range(1, MATCH_MAX + 1):
            decls, functions, result, error = clause_parts(form, n)
            push = '_Nil()'
            for i in reversed(range(n)):
                push = '_push%d(f%d, %s)' % (len(MATCH_FORMS[form]), i, push)
            subjects, leading, trailing, returns = 'subject: S', ['S: AnyType'], '', result
            if form == 'single':
                call = '_match[%s, %s](subject, %s, _Absent())' % (result, error, push)
            elif form == 'context':
                leading.append('X: AnyType')
                trailing = ',\n    *,\n    context: X'
                call = '_match[%s, %s](subject, %s, context)' % (result, error, push)
            elif form == 'pair':
                subjects, leading = 'subjects: Tuple[S0, S1]', ['S0: Movable', 'S1: Movable']
                call = '_match_all[%s, %s](subjects[0], subjects[1], _Absent(), %s)' % (result, error, push)
            elif form == 'triple':
                subjects, leading = 'subjects: Tuple[S0, S1, S2]', ['S0: Movable', 'S1: Movable', 'S2: Movable']
                call = '_match_all[%s, %s](subjects[0], subjects[1], subjects[2], %s)' % (result, error, push)
            else:
                subjects, leading, returns = 'subject: Node[F]', ['F: Data'], 'Node[F]'
                call = '_rewrite[%s](subject, %s)' % (error, push)
            name = 'rewrite' if form == 'rewrite' else '`match`'
            doc = full if n == 1 else short % n
            out.append('\n\ndef %s[\n    %s,\n    %s,\n    //\n](\n    %s,\n    %s%s\n) raises %s -> %s:\n'
                       '    """%s"""\n    return %s\n'
                       % (name, ', '.join(leading), ',\n    '.join(decls), subjects, ',\n    '.join(functions),
                          trailing, error, returns, doc, call))
    return ''.join(out) + '\n\n'


def spliced(path, text, start_marker=START, end_marker=END, header=HEADER):
    source = path.read_text()
    start = source.index(start_marker)
    end = source.index(end_marker, start) + len(end_marker)
    return source[:start] + start_marker + header + text + end_marker + source[end:]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if the sources differ from the generator')
    args = parser.parse_args()
    stale = []
    for name, expected_of in (
        ('functions/pipeline.mojo', lambda path: spliced(path, pipe_overloads())),
        ('functions/composition.mojo', lambda path: spliced(path, composition_overloads())),
        ('matching/matcher.mojo', lambda path: spliced(path, match_overloads(), MATCH_START, MATCH_END, MATCH_HEADER)),
    ):
        path = ROOT / 'src/fp' / name
        expected = expected_of(path)
        if path.read_text() != expected:
            stale.append(str(path.relative_to(ROOT)))
            if not args.check:
                path.write_text(expected)
    if args.check and stale:
        print('Out of date with scripts/generate_plain_overloads.py:', ', '.join(stale))
        return 1
    print('checked' if args.check else 'updated' if stale else 'unchanged', ', '.join(stale))
    return 0


if __name__ == '__main__':
    sys.exit(main())
