"""The suite's inventory, executables, generated drivers and independent audit.

Every test, documentation example and benchmark stays a standalone program with
its own main(). The suite groups them into a few executables: a generated driver
imports each program of its group as a top-level module and calls its main()
between marker lines. The auditor regenerates the drivers and re-derives every
outcome from the retained raw logs; reported flags are conclusions, not evidence.

Mojo 1.1 treats function types with the same spelling in different modules of one
program as one type (see native boundaries), so programs that are built together
must not spell the same function type over different same-named declarations.
Keeping the ownership tests, which mirror the runtime tests, in their own
executable avoids most such pairs.
"""
from pathlib import Path
import json
import re

from fp_tools.runtime import ROOT, PIN, accepted, audit_command, normalized, sha
from fp_tools.runs import audit_run_paths

MARK = '@@fp-suite'


def _runtime_first(stem):
    return stem.removeprefix('test_')[:1] <= 'c'


# (executable, include directories, program selection); order is run order.
SHARDS = (
    ('runtime-1', ('tests/runtime',), lambda path: _runtime_first(Path(path).stem)),
    ('runtime-2', ('tests/runtime',), lambda path: not _runtime_first(Path(path).stem)),
    ('ownership', ('tests/ownership',), None),
    ('integration', ('tests/integration', 'tests/laws', 'docs/examples', 'docs/examples/device',
                     'tests/benchmarks'), None),
)
_PROGRAMS = (('tests/runtime', 'test'), ('tests/ownership', 'test'), ('tests/integration', 'test'),
             ('tests/laws', 'test'), ('docs/examples', 'example'), ('tests/benchmarks', 'benchmark'))


def inventory(filter='', root=ROOT):
    """Every suite program, in run order, with its executable and kind."""
    examples = json.loads((root / 'docs/examples.json').read_text())['examples']
    programs = []
    for folder, kind in _PROGRAMS:
        if kind == 'example':
            paths = list(examples)
        else:
            paths = [str(p.relative_to(root)) for p in sorted((root / folder).glob('*.mojo'))]
        programs += [(path, kind) for path in paths]
    modules = []
    for name, directories, select in SHARDS:
        for path, kind in programs:
            if (str(Path(path).parent) in directories and (select is None or select(path))
                    and filter in path):
                row = dict(path=path, shard=name, kind=kind)
                if kind == 'example':
                    row['stdout'] = examples[path]['stdout']
                modules.append(row)
    return modules


def check_module_names(root=ROOT):
    """Each executable resolves its programs by module name across its directories."""
    problems = []
    for name, directories, _ in SHARDS:
        seen = {}
        for directory in directories:
            if not (root / directory).is_dir():
                continue
            for entry in sorted((root / directory).iterdir()):
                module = (entry.stem if entry.suffix == '.mojo' else
                          entry.name if (entry / '__init__.mojo').is_file() else None)
                if module is None:
                    continue
                if module in seen or module in ('fp', 'std'):
                    problems.append(f'{name}: module {module} in {directory} and {seen.get(module, "the library")}')
                seen[module] = directory
    return problems


def driver_source(shard, modules, root=ROOT):
    """One main() that runs each program's main() between markers, from `--from N` on."""
    lines = [f'"""Generated by scripts/suite.py: the {shard} executable of the FP Mojo suite."""',
             'from std.sys import argv', 'from std.time import perf_counter_ns']
    lines += [f'import {Path(m["path"]).stem}' for m in modules]
    lines += ['', '', 'def main() raises:', '    var arguments = argv()',
              '    var start = atol(arguments[2]) if len(arguments) == 3 and arguments[1] == "--from" else 0',
              '    var clock = perf_counter_ns()']
    for index, module in enumerate(modules):
        stem = Path(module['path']).stem
        passed = f'print("{MARK} pass {index}", perf_counter_ns() - clock, flush=True)'
        lines += [f'    if start <= {index}:',
                  f'        print("{MARK} begin {index} {module["path"]}", flush=True)',
                  '        clock = perf_counter_ns()']
        if re.search(r'^def main\(\) raises\b', (root / module['path']).read_text(), re.M):
            lines += ['        try:', f'            {stem}.main()', f'            {passed}',
                      '        except error:', f'            print("{MARK} fail {index}", error, flush=True)']
        else:
            lines += [f'        {stem}.main()', f'        {passed}']
    lines.append(f'    print("{MARK} end", flush=True)')
    return '\n'.join(lines) + '\n'


def build_argv(include, shard, driver, executable, werror, optimization=3):
    directories = next(d for name, d, _ in SHARDS if name == shard)
    return ['mojo', 'build', '-I', str(include), *[a for d in directories for a in ('-I', d)],
            f'-O{optimization}', *(['--Werror'] if werror else []), str(driver), '-o', str(executable)]


def run_argv(executable, start):
    return [str(executable), *(['--from', str(start)] if start else [])]


_EVENT = re.compile(rf'{MARK} (?:begin (\d+) (\S+)\n|pass (\d+) (\d+)\n|fail (\d+) |end\n)')


def parse_run(stdout):
    """Results of one raw run: ({index: result}, index of an unfinished program, ended)."""
    results, current, ended = {}, None, False
    events = list(_EVENT.finditer(stdout))
    for position, event in enumerate(events):
        following = events[position + 1].start() if position + 1 < len(events) else len(stdout)
        if ended:
            raise ValueError('output after the end marker')
        if event[1] is not None:
            if current is not None:
                raise ValueError('a program began before the previous one finished')
            current = int(event[1])
            results[current] = dict(path=event[2], start=event.end(), passed=False, error=None,
                                    nanoseconds=None)
        elif event[3] is not None or event[5] is not None:
            index = int(event[3] if event[3] is not None else event[5])
            if index != current:
                raise ValueError('out-of-order program markers')
            result = results[index]
            result['output'] = stdout[result.pop('start'):event.start()]
            if event[3] is not None:
                result.update(passed=True, nanoseconds=int(event[4]))
            else:
                result['error'] = stdout[event.end():following].rstrip('\n')
            current = None
        else:
            if current is not None:
                raise ValueError('the end marker interrupted a program')
            ended = True
    if current is not None:
        results[current]['output'] = stdout[results[current].pop('start'):]
    return results, current, ended


def fold_runs(modules, runs):
    """Outcomes of one executable's programs from its consecutive runs.

    A run that stops inside a program (a crash or timeout) fails that program;
    the next run must start right after it. Programs never reached are failed.
    The runner restarts by the same rule: after the program a run stopped in.
    """
    outcomes, start = {}, 0
    for position, record in enumerate(runs):
        results, stopped, ended = parse_run(record['stdout'])
        if record['command'][1:] != run_argv('', start)[1:]:
            raise ValueError('restart position')
        if sorted(results) != list(range(start, start + len(results))):
            raise ValueError('missing or repeated program results')
        for index, result in results.items():
            if index >= len(modules) or result['path'] != modules[index]['path']:
                raise ValueError('program identity')
            outcomes[index] = result
        if ended:
            if not accepted(record) or position != len(runs) - 1 or len(outcomes) != len(modules):
                raise ValueError('incomplete or failed final run')
            break
        if accepted(record):
            raise ValueError('a successful run without its end marker')
        if stopped is None:
            # The executable stopped between programs; the rest were not run.
            if position != len(runs) - 1:
                raise ValueError('a restart after a run that stopped between programs')
            break
        cause = 'timed out' if record['timeout'] else f'crashed (exit code {record["exit_code"]})'
        outcomes[stopped].update(passed=False, error=cause)
        start = stopped + 1
        if start == len(modules) and position != len(runs) - 1:
            raise ValueError('run after the last program')
    for index, module in enumerate(modules):
        outcomes.setdefault(index, dict(path=module['path'], passed=False, error='not run',
                                        nanoseconds=None, output=''))
    return [outcomes[index] for index in range(len(modules))]


def judge(module, outcome):
    """A test passes by finishing; an example must also print its reviewed output."""
    if module['kind'] == 'example' and outcome['passed'] and outcome['output'] != module['stdout']:
        return 'output differs from the reviewed output in docs/examples.json'
    return None if outcome['passed'] else outcome['error'] or 'failed'


_BENCH = re.compile(r'^bench (\S+) native_ns=(\d+) library_ns=(\d+) samples=(\d+)$', re.M)


def benchmark_rows(module, outcome):
    return [dict(program=module['path'], name=m[1], native_ns=int(m[2]), library_ns=int(m[3]),
                 samples=int(m[4]), ratio=round(int(m[3]) / max(int(m[2]), 1), 3))
            for m in _BENCH.finditer(outcome.get('output', ''))]


def audit_report(report, *, folder, include, filter='', werror=False, optimization=3, expected_inputs, root=ROOT):
    failures = []
    try:
        modules = inventory(filter, root)
        if not modules or [dict(path=r.get('path'), shard=r.get('shard'), kind=r.get('kind'))
                            for r in report.get('modules', [])] != [
                dict(path=m['path'], shard=m['shard'], kind=m['kind']) for m in modules]:
            failures.append('program inventory')
        if (report.get('compiler') != PIN or normalized(report.get('include'), root) != normalized(include, root)
                or report.get('filter') != filter or report.get('werror') is not werror
                or report.get('optimization') != optimization):
            failures.append('compiler/import/filter/warning/optimization policy')
        if (not expected_inputs or report.get('inputs') != expected_inputs
                or report.get('input_changes') != [] or report.get('inputs_unchanged') is not True):
            failures.append('stale/changed input binding')
        binaries = audit_run_paths(report, folder, root)
        shards = [name for name, _, _ in SHARDS if any(m['shard'] == name for m in modules)]
        records = report.get('shards', [])
        if [r.get('name') for r in records] != shards:
            failures.append('executable inventory')
            records = []
        derived = []
        for record in records:
            name, members = record['name'], [m for m in modules if m['shard'] == record['name']]
            driver = Path(folder) / 'drivers' / f'suite_{name.replace("-", "_")}.mojo'
            executable = binaries / f'fp-suite-{name}'
            if not driver.is_file() or driver.read_text() != driver_source(name, members, root):
                failures.append(f'{name}: generated driver')
            compiled = record['compilation']
            expected = build_argv(include, name, driver, executable, werror, optimization)
            if [normalized(v, root) for v in compiled['command']] != [normalized(v, root) for v in expected]:
                failures.append(f'{name}: build invocation')
            if not audit_command(compiled, root):
                failures.append(f'{name}: build raw log')
            if werror and re.search(r'\bwarning:', compiled['stdout'] + compiled['stderr'], re.I):
                failures.append(f'{name}: strict warning policy')
            if accepted(compiled):
                if not executable.is_file() or record.get('executable_sha256') != sha(executable):
                    failures.append(f'{name}: executable missing/changed')
                for run in record['runs']:
                    if not audit_command(run, root) or run['command'][0] != str(executable):
                        failures.append(f'{name}: run raw log/executable')
                outcomes = fold_runs(members, record['runs'])
            else:
                if record['runs']:
                    failures.append(f'{name}: executed an executable that did not build')
                outcomes = [dict(path=m['path'], passed=False, error='not built', output='') for m in members]
            derived += list(zip(members, outcomes))
        reported = {r.get('path'): r for r in report.get('modules', [])}
        for module, outcome in derived:
            row = reported.get(module['path'], {})
            verdict = judge(module, outcome)
            if row.get('passed') is not (verdict is None) or row.get('error') != verdict:
                failures.append(f'{module["path"]}: outcome differs from its raw log')
        benchmarks = [b for m, o in derived if m['kind'] == 'benchmark' for b in benchmark_rows(m, o)]
        if report.get('benchmarks') != benchmarks:
            failures.append('benchmark observations differ from the raw logs')
        passed = (len(derived) == len(modules) and all(judge(m, o) is None for m, o in derived
                                                        if m['kind'] != 'benchmark'))
        if report.get('passed') is not passed:
            failures.append('contradictory suite conclusion')
    except (ValueError, KeyError, TypeError, OSError, AttributeError, StopIteration) as error:
        failures.append(str(error) or type(error).__name__)
    return failures
